version: '3.1'

services:
  mysql-cocopi:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: b4afa1a2-9e6b-41d8-ac81-43a86a49bb07
      MYSQL_DATABASE: cocopi
      MYSQL_USER: cocopi
      MYSQL_PASSWORD: cocopi
    ports:
      - '3306:3306'