version: '3.1'
services:
  mongo:
    build: .
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cocopi
      - MONGO_INITDB_ROOT_PASSWORD=cocopi
      - MONGO_INITDB_DATABASE=test
      - MONGO_REPLICA_HOST=localhost
      - MONGO_REPLICA_PORT=27017
    ports:
      - '27017:27017'
