version: "3.9"

services:
  samba:
    image: docker.io/servercontainers/samba:latest
    container_name: KrakenSMB
    restart: unless-stopped
    environment:
      ACCOUNT_kraken: kraken
      UID_kraken: 1
      SAMBA_VOLUME_CONFIG_Kraken: "[sharename]; path=/shares/location; available = yes; browsable = yes; writable = no; read only = yes; public = yes; guest ok = yes"
    volumes:
      - ./test:/shares/location
    ports:
      - '445:445'
      - '139:139'
