version: "3.9"

services:
  samba:
    image: docker.io/servercontainers/samba:latest
    container_name: KrakenSMB
    restart: unless-stopped
    environment:
      ACCOUNT_kraken: smbpassword
      SAMBA_VOLUME_CONFIG_Movies: "[Movies]; comment = Kraken Bay - Movies; path=/shares/Movies; available = yes; browsable = yes; writable = no; read only = yes; public = yes; guest only = yes; create mask = 666; directory mask = 777; force user = kraken; force group = kraken"
      SAMBA_VOLUME_CONFIG_TVShows: "[TVShows]; comment = Kraken Bay - TV Shows; path=/shares/Series; available = yes; browsable = yes; writable = no; read only = yes; public = yes; guest only = yes; create mask = 666; directory mask = 777; force user = kraken; force group = kraken"
    volumes:
      - Movies
      - Series
    ports:
      - '445:445'
      - '139:139'
